In [ ]:
#Import libraries
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

: 

In [ ]:
# loading the data from the csv file to a pandas dataframe
amazon_data = pd.read_csv('./amazon.csv')
amazon_data['index'] = range(len(amazon_data))



: 

In [64]:
# printing the first 5 rows of the dataframe
amazon_data.head()

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...             ₹399   
1  Computers&Accessories|Accessories&Peripherals|...             ₹199   
2  Computers&Accessories|Accessories&Peripherals|...             ₹199   
3  Computers&Accessories|Accessories&Peripherals|...             ₹329   
4  Computers&Accessories|Accessories&Peripherals|...             ₹154   

  actual_price discount_percentage rating rating_count  \
0       ₹1,099                 64%    4.2       24,269   
1         ₹349                 43%    4.0       43,994   
2       ₹1,899                 90%    3.9        7,928   
3         ₹699                 53%    4.2       94,363   
4         ₹399                 61%    4.2       16,905   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   
2  【 Fast Charger& Data Sync】-With built-in safet...   
3  The boAt Deuce USB 300 2 in 1 cable is compati...   
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...   
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...   
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...   
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...   
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   
2  Good speed for earlier versions,Good Product,W...   
3  Good product,Good one,Nice,Really nice product...   
4  As good as original,Decent,Good one for second...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   
2  Not quite durable and sturdy,https://m.media-a...   
3  Good product,long wire,Charges good,Nice,I bou...   
4  Bought this instead of original apple, does th...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   
2  https://m.media-amazon.com/images/W/WEBP_40237...   
3  https://m.media-amazon.com/images/I/41V5FtEWPk...   
4  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  index  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...      0  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...      1  
2  https://www.amazon.in/Sounce-iPhone-Charging-C...      2  
3  https://www.amazon.in/Deuce-300-Resistant-Tang...      3  
4  https://www.amazon.in/Portronics-Konnect-POR-1...      4

In [6]:
# number of rows and columns in the data frame

amazon_data.shape

(1465, 16)

In [65]:
amazon_data = amazon_data[['index', 'product_id', 'product_name', 'category', 'about_product']]

In [66]:
amazon_data.head()

index  product_id                                       product_name  \
0      0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1      1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2      2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3      3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4      4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category  \
0  Computers&Accessories|Accessories&Peripherals|...   
1  Computers&Accessories|Accessories&Peripherals|...   
2  Computers&Accessories|Accessories&Peripherals|...   
3  Computers&Accessories|Accessories&Peripherals|...   
4  Computers&Accessories|Accessories&Peripherals|...   

                                       about_product  
0  High Compatibility : Compatible With iPhone 12...  
1  Compatible with all Type C enabled devices, be...  
2  【 Fast Charger& Data Sync】-With built-in safet...  
3  The boAt Deuce USB 300 2 in 1 cable is compati...  
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...

In [67]:
# selecting the relevant features for recommendation

selected_features = ['category','about_product','product_name','product_id']
print(selected_features)

['category', 'about_product', 'product_name', 'product_id']


In [68]:
# replacing the null valuess with null string

for feature in selected_features:
  amazon_data[feature] = amazon_data[feature].fillna('')

In [69]:
# combining all the 5 selected features

combined_features = amazon_data['category'] +amazon_data['about_product']

In [70]:
print(combined_features)

0       Computers&Accessories|Accessories&Peripherals|...
1       Computers&Accessories|Accessories&Peripherals|...
2       Computers&Accessories|Accessories&Peripherals|...
3       Computers&Accessories|Accessories&Peripherals|...
4       Computers&Accessories|Accessories&Peripherals|...
                              ...                        
1460    Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...
1461    Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...
1462    Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...
1463    Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...
1464    Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...
Length: 1465, dtype: object


In [71]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [72]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [73]:
print(feature_vectors)

  (0, 9446)	0.07527056117107593
  (0, 2773)	0.06454019130724961
  (0, 4763)	0.09252113179388696
  (0, 3343)	0.07791170859062907
  (0, 6943)	0.05434355341531045
  (0, 7144)	0.0870018967830904
  (0, 7328)	0.1033073732592662
  (0, 5930)	0.09024632538199483
  (0, 10044)	0.033841483692831395
  (0, 4930)	0.06420756310910576
  (0, 7260)	0.05187294631774002
  (0, 6485)	0.025515150554803294
  (0, 3751)	0.1048557485852527
  (0, 9096)	0.047065273595108335
  (0, 5696)	0.05060132758834444
  (0, 3761)	0.06278319588409763
  (0, 8085)	0.09173010865711378
  (0, 2989)	0.061464437814616725
  (0, 4249)	0.06505109023900786
  (0, 6185)	0.06745199170801018
  (0, 9729)	0.07481158391278397
  (0, 3791)	0.09512995388125212
  (0, 2487)	0.09173010865711378
  (0, 7213)	0.08188256827543913
  (0, 5175)	0.08760517796244166
  :	:
  (1464, 8451)	0.15475306459012822
  (1464, 5484)	0.13447239368662603
  (1464, 5035)	0.10832189738632245
  (1464, 3996)	0.10493043824080443
  (1464, 4027)	0.11817045007950247
  (1464, 8757)	0.

In [74]:
feature_names = vectorizer.get_feature_names_out()
num_dimensions = len(feature_names)
print("Dimensions of vector TF-IDF:", num_dimensions)

Dimensions of vector TF-IDF: 10079


In [75]:

# Chuyển đổi ma trận TF-IDF thành mảng
tfidf_array = feature_vectors.toarray()

In [76]:
similarity = cosine_similarity(feature_vectors)

In [77]:
print(similarity)

[[1.         0.11540629 0.22238744 ... 0.03962952 0.04637075 0.0116231 ]
 [0.11540629 1.         0.1231108  ... 0.00567602 0.01800703 0.01604121]
 [0.22238744 0.1231108  1.         ... 0.05208297 0.0440224  0.03016593]
 ...
 [0.03962952 0.00567602 0.05208297 ... 1.         0.14158094 0.0233872 ]
 [0.04637075 0.01800703 0.0440224  ... 0.14158094 1.         0.04472325]
 [0.0116231  0.01604121 0.03016593 ... 0.0233872  0.04472325 1.        ]]


In [78]:
print(similarity.shape)

(1465, 1465)


In [79]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = amazon_data['product_name'].tolist()
print(list_of_all_titles)

['Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)', 'Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)', 'Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices', 'boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)', 'Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)', 'pTron Solero TB301 3A Type-C Data and Fast Charging Cable, Made in India, 480Mbps Data Sync, Strong and Durable 1.5-Meter Nylon Braided USB Cable for Type-C Devices for Charging 

In [86]:
def recommend(product):
    if amazon_data.empty:
        print("No product available.")
        return

    # Step 1: Convert the list of product names to a list
    list_of_all_titles = amazon_data['product_name'].tolist()

    # Step 2: Find close matches to the input product name
    find_close_match = difflib.get_close_matches(product, list_of_all_titles)

    if not find_close_match:
        print("No close match found for the product. Please try another product name.")
        return

    # Step 3: Select the closest match
    close_match = find_close_match[0]

    # Step 4: Get the index of the product from the DataFrame
    index_of_the_product = amazon_data[amazon_data['product_name'] == close_match]['index'].values[0]

    # Step 5: Get the similarity scores for the product
    similarity_score = list(enumerate(similarity[index_of_the_product]))

    # Step 6: Sort the products based on similarity scores
    sorted_similar_products = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    # Step 7: Print the recommended products
    print(f'Products suggested for you based on "{close_match}":\n')

    i = 1
    for product in sorted_similar_products:
        index = product[0]
        title_from_index = amazon_data[amazon_data.index == index]['product_name'].values[0]
        if i < 30:
            print(f'{i}. {title_from_index}')
            i += 1


In [87]:
# getting the movie name from the user

productname = input(' Enter product name : ')

In [88]:
recommend(productname)

No close match found for the product. Please try another product name.
